## blog post
nimble_reversible_jump.html:  nimble_reversible_jump.Rhtml
	Rscript -e "library(nimble); library(methods); library(knitr);  knit('nimble_reversible_jump.Rhtml')"

## r-nimble.org example
reversible_jump.html:  reversible_jump.rmd
	Rscript -e "library(nimble); library(methods); rmarkdown:::render('reversible_jump.rmd')"
