---
title: "election88"
output: html_notebook
---

```{r, show = FALSE}
for (package in c('nimble', 'RCurl', 'rstan')) {
    if (!require(package, character.only = TRUE)) {
        install.packages(package)
        library(package, character.only = TRUE)
    }
}
```

# Download two data files from Stan GitHub site

```{r}
setwd(file.path(Sys.getenv('HOME'), 'nimble-dev', 'nimble-demos', 'election88'))
datFiles <- c('polls.subset.dat', 'candidate_effects.dat')
library(RCurl)
for (filename in datFiles) {
  content <- getURL(paste0("https://raw.githubusercontent.com/stan-dev/example-models/master/ARM/Ch.14/", filename))
  write(content, file = filename)
}

# This file is binary.
content <- getBinaryURL(paste0("https://raw.githubusercontent.com/stan-dev/example-models/master/ARM/Ch.14/", 'presvote.dta'))
writeBin(content, 'presvote.dta')
```
Source:
[Stan ARM Ch.17.4](https://raw.githubusercontent.com/stan-dev/example-models/master/ARM/Ch.17/17.4_multilevel_logistic_regression.R)
```{r}
library(rstan)

polls.subset <- read.table ("polls.subset.dat")
attach (polls.subset)

 # Load in data for region indicators
 # Use "state", an R data file (type ?state from the R command window for info)
 #
 # Regions:  1=northeast, 2=south, 3=north central, 4=west, 5=d.c.
 # We have to insert d.c. (it is the 9th "state" in alphabetical order)

data (state)                  # "state" is an R data file
state.abbr <- c (state.abb[1:8], "DC", state.abb[9:50])
dc <- 9
not.dc <- c(1:8,10:51)
region <- c(3,4,4,3,4,4,1,1,5,3,3,4,4,2,2,2,2,3,3,1,1,1,2,2,3,2,4,2,4,1,1,4,1,3,2,2,3,4,1,1,3,2,3,3,4,1,3,4,1,2,4)

 # define other data summaries

y <- bush                  # 1 if support bush, 0 if support dukakis
n <- length(y)             # of survey respondents
n.age <- max(age)          # of age categories
n.edu <- max(edu)          # of education categories
n.state <- max(state)      # of states
n.region <- max(region)    # of regions

 # also include a measure of previous vote as a state-level predictor

library (foreign)
presvote <- read.dta ("presvote.dta")
attach (presvote)
v.prev <- presvote$g76_84pr
age.edu <- n.edu*(age-1) + edu

ok <- !is.na(female+black+age+edu+state+y)
 # election model
dataList.1 <- list(N=length(y[ok]), n_age=n.age, n_edu=n.edu, n_region=n.region, n_state=n.state,
                   female=female[ok], black=black[ok],age=age[ok], edu=edu[ok],
                   region=region, state=state[ok],y=y[ok],v_prev=v.prev)
```
Source: [Stan book ch 17.4](http://www.stat.cmu.edu/~brian/763/GH-data/Book_Codes/ch.17/17.4_Bugs_codes.bug).
```{r}
library(nimble)
nimbleOptions(allowDynamicIndexing = TRUE)

election88_BUGS <- readBUGSmodel(nimbleCode({
    for (i in 1:n){
    y[i] ~ dbin (p.bound[i], 1)
    p.bound[i] <- max(0, min(1, p[i]))
    logit(p[i]) <- Xbeta[i]
    Xbeta[i] <- b.0 + b.female*female[i] + b.black*black[i] +
      b.female.black*female[i]*black[i] +
      b.age[age[i]] + b.edu[edu[i]] + b.age.edu[age[i],edu[i]] +
      b.state[state[i]]
  }
  b.0 ~ dnorm (0, .0001)
  b.female ~ dnorm (0, .0001)
  b.black ~ dnorm (0, .0001)
  b.female.black ~ dnorm (0, .0001)
  
  for (j in 1:n.age){b.age[j] ~ dnorm(0, tau.age)}
  for (j in 1:n.edu){b.edu[j] ~ dnorm(0, tau.edu)}
  for (j in 1:n.age){for (k in 1:n.edu){
    b.age.edu[j,k] ~ dnorm(0, tau.age.edu)}}
  for (j in 1:n.state){
    b.state[j] ~ dnorm(b.state.hat[j], tau.state)
    b.state.hat[j] <- b.region[region[j]] + b.v.prev*v.prev[j]}
  b.v.prev ~ dnorm(0, .0001)
  for (j in 1:n.region){b.region[j] ~ dnorm (0, tau.region)}

  tau.age <- pow(sigma.age, -2)
  tau.edu <- pow(sigma.edu, -2)
  tau.age.edu <- pow(sigma.age.edu, -2)
  tau.state <- pow(sigma.state, -2)
  tau.region <- pow(sigma.region, -2)

  sigma.age ~ dunif (0, 100)
  sigma.edu ~ dunif (0, 100)
  sigma.age.edu ~ dunif (0, 100)
  sigma.state ~ dunif (0, 100)
  sigma.region ~ dunif (0, 100)
}))
```
TODO(perrydv) Why does this not compile?
```{r}
electionResults1nimble <- compareMCMCs(
    list(election88_full = election88_BUGS),
    MCMCs = c('nimble'),
    niter = 1000000,
    burnin = 100000,
    thin = 1,
    summary = FALSE)

electionResults1nimble <- updateMCMCcomparisonWithHighOrderESS(
    electionResults1nimble,
    logVars = c('sigma.age','sigma.edu','sigma.age.edu','sigma.state','sigma.region'),
    includeBurninTime = FALSE)
```

