## blog post: need to check back with Perry and Chris' notes to see if need Rhtml version...
MOVEASIDEintro_bnp.html:  intro_bnp.Rhtml
	Rscript -e "library(nimble); library(methods); library(knitr);  knit('intro_bnp.Rhtml')"

## r-nimble.org example
intro_bnp.html:  intro_bnp.Rmd
	Rscript -e "library(nimble); library(methods); rmarkdown:::render('intro_bnp.Rmd')"
