intro_bnp_density.html:  intro_bnp_density.Rhtml
	Rscript -e "library(nimble); library(methods); library(knitr);  knit('intro_bnp_density.Rhtml')"
intro_bnp_raneff.html:  intro_bnp_raneff.Rhtml
	Rscript -e "library(nimble); library(methods); library(knitr);  knit('intro_bnp_raneff.Rhtml')"

## r-nimble.org example
intro_bnp.html:  intro_bnp.Rmd
	Rscript -e "library(nimble); library(methods); rmarkdown:::render('intro_bnp.Rmd')"
